os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '12'
  - '10'
dist: trusty
sudo: required
services:
  - xvfb
addons:
  sonarcloud:
    organization: "d3sd1"
    token:
      secure: "HRnTQvyty4FdiMhFG5zD36l9eMF2CPXsG0vtApb6c79CyZtb1upX7FEL+tWCFsZ0m7AQWhzqaQcOwkb3pZm4oFiwxQXZsC7g0ZeGjtA6c11x8/g2RQgBhb6WPgch5Tin67oJXjs/4vbd3jYSeybBAOZDLT4lFHmyukISEWmoqUocfBmsElyVWcfMI/0E2PSW6wVXxQS5MqurJM1BewuNVSodD5YBbHt6jsITqUFA0xD5Fq6dYnNepSXKdWP+I2b0rEjquYelEz1Y0WdOjZhDqr5PI6kA3X49hjjz6eXbY1H1W8ppgTT7QQ21A9YKRFnaqDrdleBGXSyH3n8jOYZGiRo7uBarogN02TIWtnRNuYJ1gybgD8KKbqSu/WS+w/5QIMa1wbz8VSmNoFxTnb6wsVhDXNmWk4MfXyfIXkdtO4gJBlTXRb0XninQLx73iuA7JdWCLh9D458A4lXY808qAyb7C863guZaF4An5y/jgbrcc612wYBiKS41Le+O6owsNKQbSWk0VsPjEyGU6n9jwauTcxz5i0WiXFP6ABu1bvosglpweuTnWgp8/WIlYQqd8606+aMB4bjmx0WQo98scHtnNVkTlEIwEDC6++yb4XAhT8fLgyS6nNmh5+g/7S7/cZJAQ5WZX+CXpm9UpURuAHRziNwyCL5OdGdL/1Ggu50="

before_script:
  - export DISPLAY=:99.0
install:
  - npm set progress=false
  - npm install
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
  #- ng lint
  - npm run test
  #- npm run e2e
  - npm run build
  - npm run electron:windows
  - npm run electron:mac
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_CLOSED_BETA_WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_CLOSED_BETA_WEBHOOK_URL

before_deploy:
  - git tag "$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER" --force -a -m "Travis build $TRAVIS_BUILD_NUMBER"

deploy:
  - provider: releases
    api_key: $GITHUB_OPENLOL_BETA_RELEASE_KEY
    file: "release"
    skip_cleanup: true
    tag: "experimental-$TRAVIS_BUILD_NUMBER"
    on:
      tags: false
      branch: "experimental"
  - provider: releases
    api_key: $GITHUB_OPENLOL_BETA_RELEASE_KEY
    file: "release"
    skip_cleanup: true
    tag: "beta-$TRAVIS_BUILD_NUMBER"
    on:
      tags: false
      branch: "beta"

  - provider: releases
    api_key: $GITHUB_OPENLOL_BETA_RELEASE_KEY
    file: "release"
    skip_cleanup: true
    tag: "stable-$TRAVIS_BUILD_NUMBER"
    on:
      tags: false
      branch: "stable"
