os:
  - linux
  - osx
language: node_js
node_js:
  - '12'
  - '10'
dist: trusty
sudo: required
services:
  - xvfb
addons:
  sonarcloud:
    organization: "d3sd1"
    token:
      secure: "SJRR8R9tBU18HO4wFJRjPjBQ85F3qVdM/nYNwF99/POaUSlOVrcWHDTO76ch17Z5xpXZ7sV0H8CRL+VXDj7IOMkzKQBhl3rWsQrfdFz0A3miWLD5FoRG0Ip0jtVhtGfHrZ4JC1u4f99uCkVbXnP2hMFRlGYVS3CliS1qFdWRrdh+MwZKYtBdt/pCt5C1x/RpJppFP+GhQG5dy03Q8dzJyRBW96Lol7Kz2bqawJg6cSYF7tUnt2LMEEEjB2ArajVyPXgas6ojk4BJIf1CneDLBlK/meQgMnPdO+uPRDyp3aePFkAwUVgK45tOjgai9eRLtA/M162dxDO+vhmlKBZ4mKILWqAk0EPRTC4ClCrERnL4Ppyq9/hJE1tnafttfc7dQxeb9FAtyd4P8hKTZBJwMqqpIqoIFMrQqh7fOdelU2tpGe49Mx7hNsYnqNeM0u7lOK1r9kKmAi6boeDtCT9F96Xr0W1ucQLDbbpRRg84aHlvEXHfuvbPFcrR92iPGzZdBzLdqW2QZ8XlzKbSgA3q9i3/APIcMAN052brBuf+r8UmjaLT2YFb95Dmczsthozm+a1heQnXIsOyvpmpoF/f+QckkBu2JCgySMo9P/LG/a1T00r90/WKVvhRz4BXJAhJWcOsnH/L6alTmBjdDLqWdT7tNjzwUoTyRY/nyWeZVJk="

before_script:
  - export DISPLAY=:99.0
install:
  - npm set progress=false
  - npm install
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
  #- ng lint
  - npm run test
  - npm run e2e
  - npm run build
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_CLOSED_BETA_WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_CLOSED_BETA_WEBHOOK_URL
